export const SET_TOKEN_MODAL='SET_TOKEN_MODAL'
export const GET_SHOPS_LIST=' GET_SHOPS_LIST'
export const CHANGE_ORDER_LIST=' CHANGE_ORDER_LIST'
export const CHANGE_ORDER_PAGE=' CHANGE_ORDER_PAGE'
export const GET_ORDER_LIST=' GET_ORDER_LIST'
export const SET_BOOL = 'SET_BOOL'

